export POSTGRES_USERNAME=ernest
export POSTGRES_PASSWORD=Erst24286
export POSTGRES_HOST=db-micro-service.ceelnzw9okyl.eu-west-2.rds.amazonaws.com
export POSTGRES_DB=udagram
export AWS_BUCKET=arn:aws:s3:::mircoservices-bucket
export AWS_REGION=us-west-2
export AWS_PROFILE=default
export JWT_SECRET=testing
export URL=http://localhost:8100
export DOCKER_PASSWORD = Erst24286
export DOCKER_USERNAME = ernest575
